version: '2'
services:
  healthcare-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/healthcare/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=healthcare
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
